### ISSUE TITLE
How to get informatin about hits and damage per weapon?

### ISSUE THREAD

**Issue by HarasimowiczKamil** [mikeemoo/jsgo#4]
Hi,
I know exist event on fire and death. I find in `player.getData()` information about damage per player `m_iMatchStats_Damage`. But i can't find informations about hits and damage per weapon. How to get this informations?

**Comment by robinpellegrims** [comment]
I encountered the same limitation. For example, I wanted to extract statistics on the damage done with grenades, but I'm not even sure if this information is included in the demo file?

**Comment by 0BuRner** [comment]
It's included in the demo files since 30 Juni "player_hurt" event

**Comment by HarasimowiczKamil** [comment]
Yes it is! Thx
