### ISSUE TITLE
jsgo doesn't work with new demos?

### ISSUE THREAD

**Issue by Majiick** [mikeemoo/jsgo#8]
I installed it and tried running it on a few of my demos that I recorded today, but all it's logging is "cant find entity 4" or "cant find entity 7" etc. However, jsgo works perfectly fine with the .dem that's included in the npm package. Yes, I made sure that I have the latest jsgo.

I used the round scores example.

**Comment by taylorfinnell** [comment]
I think the latest update broke the PacketEntity parsing. Specifically I think it is this line in the official parser https://github.com/csgo-data/demoinfogo-mirror/blob/2c8134c474fe7f3e02688b30249fe3cdc107ebc1/demofilepropdecode.cpp#L62 that is not implemented correctly in jsgo.

**Comment by evilnes** [comment]
The feedback node gives me is 

```
   } while (b & 0x80);
              ^
TypeError: undefined is not a function
```

which makes me guess there's static location being used somewhere, that has been offset by the recent addition of several new tables and variables.

**Comment by moritzuehling** [comment]
https://github.com/csgo-data/demoinfogo-mirror/blob/2c8134c474fe7f3e02688b30249fe3cdc107ebc1/demofilepropdecode.cpp#L51

This line also gives problems.

The other method looks like it would give wrong results, but not like it would break the parser. Have you had a look at my pull-request #9 ? What does it fix? What doesn't work?

**Comment by ghost** [comment]
Any fix?

**Comment by moritzuehling** [comment]
@nahtnam -have you tried #9?

**Comment by HarasimowiczKamil** [comment]
@moritzuehling I tried this does not solve all the problems.

**Comment by moritzuehling** [comment]
@HarasimowiczKamil What doesn't it solve? Sorry, I have no node-environment set up.

**Comment by fredricbohlin** [comment]
@moritzuehling I still get "cant find entity 3" etc with newer demos.

**Comment by itotallyrock** [comment]
Hope this gets fixed/updated/pr'd I'm really interested in using this, but I'm too scared to start if there are too many issues with it being outdated.

**Comment by saul** [comment]
If you're looking to parser newer demos, take a look at my [saul/demofile](https://github.com/saul/demofile) repo.
